INSERT INTO app_user (name, email, password) VALUES
                                                 ('Aarav Sharma', 'aarav@gmail.com', 'Password'),
                                                 ('Vivaan Khanna', 'vivaan.khanna@example.com', '$2a$10$examplePasswordHash2'),
                                                 ('Aditya Verma', 'aditya.verma@example.com', '$2a$10$examplePasswordHash3'),
                                                 ('Vihaan Kapoor', 'vihaan.kapoor@example.com', '$2a$10$examplePasswordHash4'),
                                                 ('Arjun Patel', 'arjun.patel@example.com', '$2a$10$examplePasswordHash5'),
                                                 ('Sai Reddy', 'sai.reddy@example.com', '$2a$10$examplePasswordHash6'),
                                                 ('Ananya Nair', 'ananya.nair@example.com', '$2a$10$examplePasswordHash7'),
                                                 ('Ishaan Thakur', 'ishaan.thakur@example.com', '$2a$10$examplePasswordHash8'),
                                                 ('Aryan Rao', 'aryan.rao@example.com', '$2a$10$examplePasswordHash9'),
                                                 ('Diya Singh', 'diya.singh@example.com', '$2a$10$examplePasswordHash10'),
                                                 ('Kabir Joshi', 'kabir.joshi@example.com', '$2a$10$examplePasswordHash11'),
                                                 ('Krishna Iyer', 'krishna.iyer@example.com', '$2a$10$examplePasswordHash12'),
                                                 ('Reyansh Pandey', 'reyansh.pandey@example.com', '$2a$10$examplePasswordHash13'),
                                                 ('Ayaan Mehta', 'ayaan.mehta@example.com', '$2a$10$examplePasswordHash14'),
                                                 ('Anaya Mishra', 'anaya.mishra@example.com', '$2a$10$examplePasswordHash15'),
                                                 ('Navya Kulkarni', 'navya.kulkarni@example.com', '$2a$10$examplePasswordHash16'),
                                                 ('Naira Desai', 'naira.desai@example.com', '$2a$10$examplePasswordHash17'),
                                                 ('Dhruv Saxena', 'dhruv.saxena@example.com', '$2a$10$examplePasswordHash18'),
                                                 ('Sara Bajaj', 'sara.bajaj@example.com', '$2a$10$examplePasswordHash19'),
                                                 ('Arnav Malhotra', 'arnav.malhotra@example.com', '$2a$10$examplePasswordHash20'),
                                                 ('Rahul Kumar', 'rahul.kumar@example.com', '$2a$10$examplePasswordHash21'),
                                                 ('Rohit Gupta', 'rohit.gupta@example.com', '$2a$10$examplePasswordHash22'),
                                                 ('Pooja Sharma', 'pooja.sharma@example.com', '$2a$10$examplePasswordHash23'),
                                                 ('Karan Singh', 'karan.singh@example.com', '$2a$10$examplePasswordHash24'),
                                                 ('Sonia Mehta', 'sonia.mehta@example.com', '$2a$10$examplePasswordHash25'),
                                                 ('Anil Kapoor', 'anil.kapoor@example.com', '$2a$10$examplePasswordHash26'),
                                                 ('Deepak Verma', 'deepak.verma@example.com', '$2a$10$examplePasswordHash27'),
                                                 ('Sneha Jain', 'sneha.jain@example.com', '$2a$10$examplePasswordHash28'),
                                                 ('Ajay Mishra', 'ajay.mishra@example.com', '$2a$10$examplePasswordHash29'),
                                                 ('Nisha Reddy', 'nisha.reddy@example.com', '$2a$10$examplePasswordHash30'),
                                                 ('Vikas Joshi', 'vikas.joshi@example.com', '$2a$10$examplePasswordHash31'),
                                                 ('Meena Desai', 'meena.desai@example.com', '$2a$10$examplePasswordHash32'),
                                                 ('Rajesh Iyer', 'rajesh.iyer@example.com', '$2a$10$examplePasswordHash33'),
                                                 ('Suresh Nair', 'suresh.nair@example.com', '$2a$10$examplePasswordHash34'),
                                                 ('Kavita Singh', 'kavita.singh@example.com', '$2a$10$examplePasswordHash35'),
                                                 ('Ankur Saxena', 'ankur.saxena@example.com', '$2a$10$examplePasswordHash36'),
                                                 ('Geeta Bajaj', 'geeta.bajaj@example.com', '$2a$10$examplePasswordHash37'),
                                                 ('Ramesh Malhotra', 'ramesh.malhotra@example.com', '$2a$10$examplePasswordHash38'),
                                                 ('Seema Rao', 'seema.rao@example.com', '$2a$10$examplePasswordHash39'),
                                                 ('Tarun Sharma', 'tarun.sharma@example.com', '$2a$10$examplePasswordHash40');

INSERT INTO user_roles (user_id, roles) VALUES
                                            (1, 'RIDER'),
                                            (2, 'RIDER'),
                                            (2, 'DRIVER'),
                                            (3, 'RIDER'),
                                            (3, 'DRIVER'),
                                            (4, 'RIDER'),
                                            (4, 'DRIVER'),
                                            (5, 'RIDER'),
                                            (5, 'DRIVER'),
                                            (6, 'RIDER'),
                                            (6, 'DRIVER'),
                                            (7, 'RIDER'),
                                            (7, 'DRIVER'),
                                            (8, 'RIDER'),
                                            (8, 'DRIVER'),
                                            (9, 'RIDER'),
                                            (9, 'DRIVER'),
                                            (10, 'RIDER'),
                                            (10, 'DRIVER'),
                                            (11, 'RIDER'),
                                            (11, 'DRIVER'),
                                            (12, 'RIDER'),
                                            (12, 'DRIVER'),
                                            (13, 'RIDER'),
                                            (13, 'DRIVER'),
                                            (14, 'RIDER'),
                                            (14, 'DRIVER'),
                                            (15, 'RIDER'),
                                            (15, 'DRIVER'),
                                            (16, 'RIDER'),
                                            (16, 'DRIVER'),
                                            (17, 'RIDER'),
                                            (17, 'DRIVER'),
                                            (18, 'RIDER'),
                                            (18, 'DRIVER'),
                                            (19, 'RIDER'),
                                            (19, 'DRIVER'),
                                            (20, 'RIDER'),
                                            (20, 'DRIVER'),
                                            (21, 'RIDER'),
                                            (21, 'DRIVER'),
                                            (22, 'RIDER'),
                                            (22, 'DRIVER'),
                                            (23, 'RIDER'),
                                            (23, 'DRIVER'),
                                            (24, 'RIDER'),
                                            (24, 'DRIVER'),
                                            (25, 'RIDER'),
                                            (25, 'DRIVER'),
                                            (26, 'RIDER'),
                                            (26, 'DRIVER'),
                                            (27, 'RIDER'),
                                            (27, 'DRIVER'),
                                            (28, 'RIDER'),
                                            (28, 'DRIVER'),
                                            (29, 'RIDER'),
                                            (29, 'DRIVER'),
                                            (30, 'RIDER'),
                                            (30, 'DRIVER'),
                                            (31, 'RIDER'),
                                            (31, 'DRIVER'),
                                            (32, 'RIDER'),
                                            (32, 'DRIVER'),
                                            (33, 'RIDER'),
                                            (33, 'DRIVER'),
                                            (34, 'RIDER'),
                                            (34, 'DRIVER'),
                                            (35, 'RIDER'),
                                            (35, 'DRIVER'),
                                            (36, 'RIDER'),
                                            (36, 'DRIVER'),
                                            (37, 'RIDER'),
                                            (37, 'DRIVER'),
                                            (38, 'RIDER'),
                                            (38, 'DRIVER'),
                                            (39, 'RIDER'),
                                            (39, 'DRIVER'),
                                            (40, 'RIDER'),
                                            (40, 'DRIVER');

INSERT INTO rider ( user_id, rating) VALUES
    ( 1, 4.9);

INSERT INTO driver (user_id, rating, available, current_location) VALUES
                                                                          (2, 4.7, true, ST_GeomFromText('POINT(73.8567 18.5204)', 4326)),
                                                                          (3, 4.8, true, ST_GeomFromText('POINT(73.8500 18.5100)', 4326)),
                                                                          (4, 4.6, true, ST_GeomFromText('POINT(73.8470 18.5070)', 4326)),
                                                                          (5, 4.9, true, ST_GeomFromText('POINT(73.8400 18.5000)', 4326)),
                                                                          (6, 4.3, true, ST_GeomFromText('POINT(73.8300 18.4800)', 4326)),
                                                                          (7, 4.4, true, ST_GeomFromText('POINT(73.8200 18.4900)', 4326)),
                                                                          (8, 4.5, true, ST_GeomFromText('POINT(73.8100 18.4700)', 4326)),
                                                                          (9, 4.6, true, ST_GeomFromText('POINT(73.8000 18.4600)', 4326)),
                                                                          (10, 4.7, true, ST_GeomFromText('POINT(73.8500 18.4500)', 4326)),
                                                                          (11, 4.8, true, ST_GeomFromText('POINT(73.8600 18.4400)', 4326)),
                                                                          (12, 4.2, true, ST_GeomFromText('POINT(73.8700 18.4300)', 4326)),
                                                                          (13, 4.1, true, ST_GeomFromText('POINT(73.8800 18.4200)', 4326)),
                                                                          (14, 4.0, true, ST_GeomFromText('POINT(73.8900 18.4100)', 4326)),
                                                                          (15, 4.5, true, ST_GeomFromText('POINT(73.9000 18.4000)', 4326)),
                                                                          (16, 4.3, true, ST_GeomFromText('POINT(73.9100 18.3900)', 4326)),
                                                                          (17, 4.6, true, ST_GeomFromText('POINT(73.9200 18.3800)', 4326)),
                                                                          (18, 4.4, true, ST_GeomFromText('POINT(73.9300 18.3700)', 4326)),
                                                                          (19, 4.7, true, ST_GeomFromText('POINT(73.9400 18.3600)', 4326)),
                                                                          (20, 4.8, true, ST_GeomFromText('POINT(73.9500 18.3500)', 4326)),
                                                                          (21, 4.5, true, ST_GeomFromText('POINT(73.9600 18.3400)', 4326)),
                                                                          (22, 4.7, true, ST_GeomFromText('POINT(73.9700 18.3300)', 4326)),
                                                                          (23, 4.8, true, ST_GeomFromText('POINT(73.9800 18.3200)', 4326)),
                                                                          (24, 4.6, true, ST_GeomFromText('POINT(73.9900 18.3100)', 4326)),
                                                                          (25, 4.9, true, ST_GeomFromText('POINT(74.0000 18.3000)', 4326)),
                                                                          (26, 4.3, true, ST_GeomFromText('POINT(74.0100 18.2900)', 4326)),
                                                                          (27, 4.4, true, ST_GeomFromText('POINT(74.0200 18.2800)', 4326));
INSERT INTO wallet ( user_id, balance) VALUES
                                              (1, 100),
                                              (2, 500);